version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - development 
  api:
    build:
      dockerfile: Dockerfile
      context: . 
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env 
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - development
    depends_on:
      - redis
      - postgres

  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - development

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  development:
    external: true